name: Count Visits

on:
  repository_dispatch:
    types: [increment_visit]

jobs:
  update-counter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update visits.json
        run: |
          VISITS=$(jq '.visits + 1' visits.json)
          echo "{\"visits\": $VISITS}" > visits.json

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add visits.json
          git commit -m "Visit recorded at $(date)"
          git push
